# Compilation.ps1
# Deterministically compile ordered shared modules into a runtime document.
# Requires Common.ps1 and Configuration.ps1 to be dot-sourced first.

Set-StrictMode -Version Latest

function Format-GeneratedWarning {
    return @(
        '> Generated from the Universal Agent System.',
        '> Do not edit this file directly.',
        '> Edit the shared source modules under core/, workflows/, capabilities/, and memory/, then rebuild.'
    ) -join "`n"
}

function Format-RuntimeHeader {
    param([Parameter(Mandatory)]$Adapter)
    $lines = @($Adapter.document.runtimeHeader)
    return ($lines -join "`n")
}

function Format-SourceMarker {
    param([Parameter(Mandatory)][string]$RelativePath)
    return ("<!-- source: {0} -->" -f $RelativePath)
}

function Get-ModuleContent {
    <# Read a module, normalize to LF, and trim surrounding blank lines. #>
    param([Parameter(Mandatory)][string]$Path)
    $raw = Read-TextFileRaw -Path $Path
    $lf = $raw -replace "`r`n", "`n" -replace "`r", "`n"
    return $lf.Trim("`n")
}

function Build-RuntimeDocument {
    <#
        Compile the runtime document as a single LF-normalized string.
        Byte encoding and final line endings are applied by the caller via ConvertTo-AgentBytes.
    #>
    param(
        [Parameter(Mandatory)]$AgentConfig,
        [Parameter(Mandatory)]$Adapter,
        [Parameter(Mandatory)][string]$RepoRoot
    )

    $comp = $AgentConfig.compilation
    $parts = New-Object System.Collections.Generic.List[string]

    if ($comp.includeGeneratedWarning) {
        $parts.Add((Format-GeneratedWarning))
    }

    $parts.Add(("# {0}" -f $Adapter.document.title))

    $header = Format-RuntimeHeader -Adapter $Adapter
    if (-not [string]::IsNullOrWhiteSpace($header)) {
        $parts.Add($header)
    }

    $modules = Get-ModulePathList -AgentConfig $AgentConfig -RepoRoot $RepoRoot
    foreach ($m in $modules) {
        if (-not (Test-Path -LiteralPath $m.Absolute)) {
            throw "Module missing during compilation: $($m.Relative)"
        }
        $block = ''
        if ($comp.includeSourceMarkers) {
            $block += (Format-SourceMarker -RelativePath $m.Relative) + "`n`n"
        }
        $block += (Get-ModuleContent -Path $m.Absolute)
        $parts.Add($block)
    }

    # Join blocks with a blank line; guarantee a single trailing newline.
    $doc = ($parts -join "`n`n")
    $doc = $doc.TrimEnd("`n") + "`n"
    return $doc
}
